services:
  app1:
    image: nginx:latest
    container_name: app1_bai14
    restart: always
    networks:
      - private_network

  app2:
    image: nginx:latest
    container_name: app2_bai14
    restart: always
    networks:
      - private_network

networks:
  private_network:
    driver: bridge
