version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis_broker_bai8
    ports:
      - "6379:6379"

  django_app:
    build: .
    container_name: django_app_bai8
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery_worker:
    build: .
    container_name: celery_worker_bai8
    command: celery -A core worker -l info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - django_app
      - redis
